### ISSUE TITLE
linkaja example is not working

### ISSUE THREAD

**Issue by bokunodev** [xendit/xendit-python#22]
5.3.0-rc8-0.8-MANJARO-ARM (arm64)
Python 3.8.2
```Python
from xendit import EWallet, LinkAjaItem
import json

barang = []
lajaitem = LinkAjaItem(
    id="123123",
    name="Phone Case",
    price=100000,
    quantity=1)
barang.append(lajaitem)
linkaja_payment = EWallet.create_linkaja_payment(
    external_id="linkaja-ewallet-test-1593663498",
    phone="089911111111",
    items=barang,
    amount=300000,
    callback_url="https://my-shop.com/callbacks",
    redirect_url="https://xendit.co/",
)
print(barang)
print(json.dumps(barang))
print(linkaja_payment)
```
output :
```
Traceback (most recent call last):
  File "temp.py", line 11, in <module>
    linkaja_payment = EWallet.create_linkaja_payment(
  File "/home/bokuno/Public/akuncenter/venv/lib/python3.8/site-packages/xendit/models/ewallet/ewallet.py", line 187, in create_linkaja_payment
    resp = _APIRequestor.post(url, **kwargs)
  File "/home/bokuno/Public/akuncenter/venv/lib/python3.8/site-packages/xendit/_api_requestor.py", line 20, in post
    return _APIRequestor._request("POST", url, **kwargs)
  File "/home/bokuno/Public/akuncenter/venv/lib/python3.8/site-packages/xendit/_api_requestor.py", line 59, in _request
    resp = http_client.request(method, url, headers=headers, json=body)
  File "/home/bokuno/Public/akuncenter/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bokuno/Public/akuncenter/venv/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/home/bokuno/Public/akuncenter/venv/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/home/bokuno/Public/akuncenter/venv/lib/python3.8/site-packages/requests/models.py", line 317, in prepare
    self.prepare_body(data, files, json)
  File "/home/bokuno/Public/akuncenter/venv/lib/python3.8/site-packages/requests/models.py", line 467, in prepare_body
    body = complexjson.dumps(json)
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type LinkAjaItem is not JSON serializable
```

**Comment by bokunodev** [comment]
## with __dict__
```Python
from xendit import EWallet, LinkAjaItem
import json

barang = []
lajaitem = LinkAjaItem(
    id="123123",
    name="Phone Case",
    price=100000,
    quantity=1)
barang.append(lajaitem.__dict__)
linkaja_payment = EWallet.create_linkaja_payment(
    external_id="linkaja-ewallet-test-1593663498",
    phone="089911111111",
    items=barang,
    amount=300000,
    callback_url="https://my-shop.com/callbacks",
    redirect_url="https://xendit.co/",
)
print(barang)
print(json.dumps(barang))
print(linkaja_payment)
```
```
Traceback (most recent call last):
  File "temp.py", line 11, in <module>
    linkaja_payment = EWallet.create_linkaja_payment(
  File "/home/bokuno/Public/akuncenter/venv/lib/python3.8/site-packages/xendit/models/ewallet/ewallet.py", line 191, in create_linkaja_payment
    raise XenditError(resp)
xendit.xendit_error.XenditError: There was an error with the format submitted to the server.
```

**Comment by adyaksaw** [comment]
Hello @bokunodev ! For the first example, you can use `EWallet.helper_create_linkaja_item` instead of directly instantiating the `LinkAjaItem`. It's not intended to directly instantiate any of the object for the parameters.

For the `__dict__` example, your request are successfully send, but the server send the error because you're not inserting the API key. Use this code example instead if you want to use `dict` directly:

```
from xendit import Xendit

xendit_instance = Xendit(api_key='YOUR-API-KEY')
EWallet = xendit_instance.EWallet
barang = []
barang.append({
    "id": "123123",
    "name": "Phone Case",
    "price": 100000,
    "quantity": 1,
})
linkaja_payment = EWallet.create_linkaja_payment(
    external_id="linkaja-ewallet-test-1593663498",
    phone="089911111111",
    items=barang,
    amount=300000,
    callback_url="https://my-shop.com/callbacks",
    redirect_url="https://xendit.co/",
)
print(linkaja_payment)
```

**Comment by bokunodev** [comment]
ok, it fixed now.
thanks for the feed back.

**Comment by bokunodev** [comment]
did the other example may have the same issue ?

**Comment by adyaksaw** [comment]
Yes we're currently rechecking the readme so we don't find that problem again. If you found another problem you can create another issue so we will know about it faster

**Comment by adityarx** [comment]
Closing this as resolved~
